feat: button for background music
edgarberlinck/bar-figth-game pull request #3
Opened 2022-10-24 01:21 UTC by CarlosJunioor

- [ ] added button that plays background music
- [ ] everytime you click the button its a random song

Things to improve
- Remove the button
- Learn how to optimize the code.

2022-10-24 09:21 UTC, edgarberlinck requested changes
Está bem legal para uma primeira versão. Algumas coisas que seriam legais no futuro:

- Padronizar o nome do arquivo Mp3
- Tipar a lista de musica e ter mais informações como artista e nome da musica.
- Ler o diretório antes de iniciar o game e carregar as músicas. 
- Ao carregar as musicas podemos obter as informações da Id3Tag (Ou nome do arquivo)
- Ter um botão para pular a música
- Melhorar esse shuffle das musicas para evitar que a gente fique tocando as mesma musicas. O ideal seria gerar uma playlist aleatória no inicio do game a tocar ela sem parar. Lembre-se que isso vai ficar dentro no `animationLoop` e pode ser que esses cálculos podem não acontecer da forma que espera

2022-10-24 09:21 UTC, edgarberlinck commented on index.html
> +      <audio id="myAudio">
Vamos usar um id mais legal? Use `background-music`

2022-10-24 09:21 UTC, edgarberlinck commented on src/game.ts
> +  playlist[0] = './public/assets/songs/BB.mp3'
Pode tirar o `/public`. Ele não é necessário.

2022-10-24 09:21 UTC, edgarberlinck commented on src/game.ts
> +  playlist[41] = './public/assets/songs/Riot In The Discoteque.mp3'
Eu percebi que as músicas dos Plasmatics foram renomeadas (tinha um ' no meio do nome). Foi isso mesmo?

2022-10-24 09:21 UTC, edgarberlinck commented on index.html
> +      <audio id="myAudio">
Pelo que vi no código não é necessário colocar esse id já que você não esta utilizando ele para manipular o elemento.

2022-10-24 09:28 UTC, edgarberlinck commented on src/game.ts
> +  playlist[41] = './public/assets/songs/Riot In The Discoteque.mp3'
Te pergunto isso em específico pois notei que essas músicas nāo estão mais no repositório.

2022-10-24 16:07 UTC, CarlosJunioor commented on index.html
> +      <audio id="myAudio">
Então, essa parte que eu mudei no ficheiro index.html foi erro meu, esse código não muda nem é relavante eu deixei como tava, e obg nem tinha visto q tinha deixado essa parte no código.

2022-10-24 16:09 UTC, CarlosJunioor commented on src/game.ts
> +  playlist[0] = './public/assets/songs/BB.mp3'
corrigido!

2022-10-24 16:12 UTC, CarlosJunioor commented on src/game.ts
> +  playlist[41] = './public/assets/songs/Riot In The Discoteque.mp3'
Então oq aconteceu foi, eu tava tentando chamar essas músicas no array playlist[] só devido a essas musicas terem ' no nome eu não conseguia fazer isso e decide renomear todas essas musicas e remover esse ', porém não sabia q isso iria remover as músicas.

Faço um commit dessas músicas então?

2022-10-24 16:12 UTC, CarlosJunioor commented on index.html
> +      <audio id="myAudio">
Exato!

2022-10-24 16:43 UTC, CarlosJunioor commented
Foi erro meu também, não ter feito uma branch para ter adicionado esse feat.

2022-10-26 20:08 UTC, edgarberlinck approved these changes

2022-10-26 20:08 UTC, merged